[[ISSUERS]]
address = "rUBApZm1wv31WZ8PZCiTGH2tHWRDwRA3oU"
name = "XET ET ON XRP"

[[TOKENS]]
issuer = "rUBApZm1wv31WZ8PZCiTGH2tHWRDwRA3oU"
currency = "XET"
name = "XET ET ON XRP"
desc = ""
icon = "https://xumm.app/assets/icons/currencies/ex-csc-3.png"

[[TOKENS.WEBLINKS]]
url = "https://www.google.com"
type = "website"
title = "Official Website"

[[TOKENS.WEBLINKS]]
url = "https://www.tiktok.com"
type = "website"
title = "Telegram"

[[TOKENS.WEBLINKS]]
url = "https://www.tiktok.com"
type = "socialmedia"
